### ISSUE TITLE
How to set seed?

### ISSUE THREAD

**Issue by jeffallen** [GoogleCloudPlatform/cassandra-docker#2]
I am using this image in a DaemonSet, in order to run one Cassandra on every node in my cluster. They come up ok, but they each stand alone, and do not form a cluster.

https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra has a way of setting the seed from a k8s API. Does this image use some other way of doing it?

Basically, I can't tell if this is supported but not documented well, or if this image is meant to only run a 1 node cassandra "cluster".

**Comment by drinkius** [comment]
Any updates?

**Comment by jprzychodzen** [comment]
Thank you for submitting this issue.

To run Cassandra as a cluster, please make use of following sample:
```
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: cassandra
  labels: &CassandraDeploymentLabels
    name: "cassandra"
spec:
  selector:
    matchLabels: *CassandraDeploymentLabels
  serviceName: cassandra-svc
  replicas: 3
  template:
    metadata:
      labels: *CassandraDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: cassandra
        image: launcher.gcr.io/google/cassandra3:latest
        imagePullPolicy: Always
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: cassandra-svc
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra-svc.default.svc.cluster.local, cassandra-1.cassandra-svc.default.svc.cluster.local, cassandra-2.cassandra-svc.default.svc.cluster.local
        ports:
        - name: pure-intra
          containerPort: 7000
        - name: tls-intra
          containerPort: 7001
        - name: jmx
          containerPort: 7199
        - name: cql
          containerPort: 9042
        - name: thrift
          containerPort: 9160
        resources:
          limits:
            cpu: 1
            memory: 3Gi
          requests:
           cpu: 1
           memory: 3Gi
        volumeMounts:
        - name: cassandra-pvc
          mountPath: /var/lib/cassandra
        livenessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        readinessProbe:
          exec:
            command: [ "/bin/sh", "-c", "nodetool status | grep -E \"^UN\\s+${POD_IP}\"" ]
          initialDelaySeconds: 90
          periodSeconds: 30
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - "nodetool drain"
  volumeClaimTemplates:
  - metadata:
      name: cassandra-pvc
      labels: *CassandraDeploymentLabels
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  labels:
    name: "cassandra"
spec:
  ports:
  - name: cql
    port: 9042
  - name: thrift
    port: 9160
  selector:
    name: "cassandra"
  type: ClusterIP
  clusterIP: None
```

Seed node can be set using environment variable  `CASSANDRA_SEEDS`, that can accept a list of seeds.

While using `DaemonSet`, please be aware that hostname is not know, as cannot be provided in the configuration. DNS scrapping is required, to extract ip addresses, as described in [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#communicating-with-daemon-pods) documentaction.
